name: iwms_citizen_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core App Packages ---
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  get_it: ^8.2.0
  equatable: ^2.0.7
  intl: ^0.20.2
  http: ^1.2.2
  
  # --- UI & Utilities ---
  smooth_page_indicator: ^1.2.1
  animated_bubble_navigation_bar: ^1.1.0
  motion_tab_bar: ^2.0.4
  smooth_sheets: ^0.15.0
  rive: ^0.13.20
  animations: ^2.0.11
  google_fonts: ^6.2.1        # <-- UPGRADED
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.1.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.5.3 
  graphic: ^2.5.0

  # --- Module 1 (Citizen) Packages ---
  flutter_map: ^7.0.1          # <-- UPGRADED
  latlong2: ^0.9.1            # <-- UPGRADED
  flutter_local_notifications: 19.5.0
  # --- Module 3 (Operator) Packages ---
  mobile_scanner: ^6.0.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  flutter_bluetooth_serial: ^0.4.0 
  wakelock_plus: ^1.2.8
  flutter_tts: ^4.2.2
  geocoding: ^4.0.0
  neumorphic_button: ^0.0.1+2
  table_calendar: ^3.0.9
  animated_neumorphic: ^0.2.0
  camera: ^0.11.0
  lucide_icons: ^0.257.0
  connectivity_plus: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # <-- UPGRADED
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_bg.png" 
  min_sdk_android: 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/cards/
    - assets/gif/
    - assets/rive/
    - assets/banner/
    - asset/images/
    - assets/intro/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
